apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: harbor-local
      containers:
      - image: redis:6.2.6
        name:  redis
        ports:
        - containerPort: 6379
        command: ["redis-server", "/conf/redis.conf"]
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        configMap:
          name: redis-config
          defaultMode: 0755
